### ISSUE TITLE
API Key Hardcoded

### ISSUE THREAD

**Issue by xmakina** [simonstaton/community-radio#15]
The API Key should come from the .env or some other configuration file

**Comment by xmakina** [comment]
Also the MongoDB location

**Comment by BernardoSilva** [comment]
Hi @xmakina ,

Thank you for your ticket and contribution.
We've added your suggestion to the project in [153aa72](https://github.com/simonstaton/community-radio/pull/31/commits/153aa72827189ce00908b5d7ab07b7fc17d45f80)

Hope this is a bit easier to setup now.
