### ISSUE TITLE
Bug: playlist name and search song text should have another colour for better UI

### ISSUE THREAD

**Issue by osavchenko** [simonstaton/community-radio#21]

**Comment by zsturgess** [comment]
![screenshot from 2016-05-04 12 47 12](https://cloud.githubusercontent.com/assets/3624596/15013259/7617adb6-11f6-11e6-8ff9-f29706f042e8.png) Yeah, it's pretty hard to see! :+1:

**Comment by BernardoSilva** [comment]
will have proper design tickets
