### ISSUE TITLE
Feature: Removing tracks from playlist

### ISSUE THREAD

**Issue by OwenPattison** [simonstaton/community-radio#7]
Remove song button in playlist removes the last track added rather than selected track

**Comment by simonstaton** [comment]
Was getting the wrong track index, should be good now.

**Comment by OwenPattison** [comment]
Hey Simon, looks like the problem has regressed, also when you do remove a track the playlist automatically saves

**Comment by simonstaton** [comment]
Looks like it has, the issue with saving is that the playlist does not re-fetch from the db when you reopen it. you can remove a track if it has been saved, its only when you have just added it, should have a fix later tonight
